---
- name: "Load Config on localhost"
  hosts: localhost
  tags:
    - config
  tasks:
    - name: "Load Config on localhost"
      include_vars:
        file: ./config.yml

- import_playbook: "./autoscaler/remove.yml"
  tags:
    - kubernetes
    - k8s
    - autoscaler

- import_playbook: "./redis/remove.yml"
  tags:
    - kubernetes
    - k8s
    - redis

- import_playbook: "./services/remove.yml"
  tags:
    - kubernetes
    - k8s
    - sequencer

- import_playbook: "./checklists/remove.yml"
  tags:
    - kubernetes
    - k8s
    - checklists

- import_playbook: "./fluentd/remove.yml"
  tags:
    - kubernetes
    - k8s
    - fluentd
    - logging
    - log
  when: fluentd.enabled == true

- import_playbook: "./kubernetes/remove.yml"
  tags:
    - kubernetes
    - k8s
    - setup
